language: csharp
solution: Tracery.Net.sln
install:
  - nuget restore Tracery.Net.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Tracery.Net.sln
  - mono ./testrunner/NUnit.Runners.3.5.0/tools/nunit-console.exe ./Tests/bin/Release/Tests.dll