language: csharp
solution: Tracery.Net.sln
install:
  - nuget restore Tracery.Net.sln
  - nuget install NUnit.Console -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Tracery.Net.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll